import 'package:flutter/material.dart';import 'package:provider/provider.dart';import '../core/api_exception.dart';import '../core/roles.dart';import '../core/session.dart';import '../models/entity_config.dart';import '../models/page_result.dart';import '../repositories/pb_repository.dart';import '../widgets/page_frame.dart';import '../widgets/state_views.dart';
class GenericCrudScreen extends StatefulWidget{const GenericCrudScreen({super.key,required this.config});final EntityConfig config;@override State<GenericCrudScreen> createState()=>_S();}
class _S extends State<GenericCrudScreen>{PageResult<Map<String,dynamic>>? page;String? error;final selected=<String>{};@override void initState(){super.initState();load();}@override void didUpdateWidget(covariant GenericCrudScreen old){super.didUpdateWidget(old);if(old.config.collection!=widget.config.collection){page=null;selected.clear();load();}}
Future<void> load()async{try{final r=await context.read<PbRepository>().list(widget.config.collection,perPage:100,sort:'-created');if(mounted)setState((){page=r;error=null;});}on ApiException catch(e){if(mounted)setState(()=>error=e.message);}}
Future<void> edit([Map<String,dynamic>? record])async{final ok=await showDialog<bool>(context:context,builder:(_)=>RecordDialog(config:widget.config,record:record));if(ok==true)load();}
Future<void> bulk()async{await context.read<PbRepository>().bulkSoftDelete(widget.config.collection,selected.toList());selected.clear();load();}
@override Widget build(BuildContext context){if(page==null&&error==null)return const LoadingView();if(error!=null)return ErrorView(message:error!,onRetry:load);final admin=Permissions.canHardDelete(context.watch<Session>().role);return PageFrame(child:Column(children:[Row(children:[Expanded(child:Text(widget.config.title,style:Theme.of(context).textTheme.headlineSmall)),if(selected.isNotEmpty)OutlinedButton.icon(onPressed:bulk,icon:const Icon(Icons.delete_sweep),label:Text('Удалить (${selected.length})')),const SizedBox(width:8),FilledButton.icon(onPressed:()=>edit(),icon:const Icon(Icons.add),label:const Text('Добавить'))]),const SizedBox(height:12),Expanded(child:ListView.separated(itemCount:page!.items.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(context,i){final r=page!.items[i];final id='${r['id']}';final deleted=r['deleted']==true;return ListTile(leading:Checkbox(value:selected.contains(id),onChanged:(v)=>setState(()=>v==true?selected.add(id):selected.remove(id))),title:Text('${r[widget.config.displayField]??id}',style:deleted?const TextStyle(decoration:TextDecoration.lineThrough):null),subtitle:Text(id),trailing:Wrap(children:[if(!deleted)IconButton(tooltip:'Редактировать',onPressed:()=>edit(r),icon:const Icon(Icons.edit_outlined)),if(!deleted)IconButton(tooltip:'Логически удалить',onPressed:()async{await context.read<PbRepository>().softDelete(widget.config.collection,id);load();},icon:const Icon(Icons.delete_outline)),if(deleted)IconButton(tooltip:'Восстановить',onPressed:()async{await context.read<PbRepository>().restore(widget.config.collection,id);load();},icon:const Icon(Icons.restore)),if(deleted&&admin)IconButton(tooltip:'Удалить физически',onPressed:()async{await context.read<PbRepository>().delete(widget.config.collection,id);load();},icon:const Icon(Icons.delete_forever))]));}))]));}}

class RecordDialog extends StatefulWidget{const RecordDialog({super.key,required this.config,this.record});final EntityConfig config;final Map<String,dynamic>? record;@override State<RecordDialog> createState()=>_R();}
class _R extends State<RecordDialog>{final form=GlobalKey<FormState>();final ctrls=<String,TextEditingController>{};final bools=<String,bool>{};final relations=<String,String?>{};final options=<String,List<Map<String,dynamic>>>{};final multi=<String,Set<String>>{};Map<String,String> server={};bool saving=false;
@override void initState(){super.initState();for(final f in widget.config.fields){final v=widget.record?[f.name];switch(f.kind){case FieldKind.boolean:bools[f.name]=v==true;break;case FieldKind.relation:relations[f.name]=v==null||'$v'.isEmpty?null:'$v';loadOptions(f);break;case FieldKind.multiRelation:multi[f.name]=((v as List?)??const[]).map((e)=>'$e').toSet();loadOptions(f);break;case FieldKind.text:case FieldKind.number:ctrls[f.name]=TextEditingController(text:v==null?'':'$v');break;}}}
Future<void> loadOptions(FieldConfig f)async{if(f.relationCollection==null)return;try{final r=await context.read<PbRepository>().list(f.relationCollection!,perPage:200,sort:f.relationLabelField);if(mounted)setState(()=>options[f.name]=r.items);}catch(_){}}
@override void dispose(){for(final c in ctrls.values)c.dispose();super.dispose();}
Future<void> save()async{setState(()=>server={});if(!form.currentState!.validate())return;final data=<String,dynamic>{'deleted':false};for(final f in widget.config.fields){switch(f.kind){case FieldKind.text:data[f.name]=ctrls[f.name]!.text.trim();break;case FieldKind.number:data[f.name]=double.tryParse(ctrls[f.name]!.text.trim())??0;break;case FieldKind.boolean:data[f.name]=bools[f.name]??false;break;case FieldKind.relation:data[f.name]=relations[f.name];break;case FieldKind.multiRelation:data[f.name]=multi[f.name]?.toList()??<String>[];break;}}setState(()=>saving=true);try{if(widget.record==null)await context.read<PbRepository>().create(widget.config.collection,data);else await context.read<PbRepository>().update(widget.config.collection,'${widget.record!['id']}',data);if(mounted)Navigator.pop(context,true);}on ApiException catch(e){if(mounted)setState(()=>server=e.fieldErrors);form.currentState!.validate();}finally{if(mounted)setState(()=>saving=false);}}
@override Widget build(BuildContext context)=>AlertDialog(title:Text(widget.record==null?'Новая запись':'Редактирование'),content:SizedBox(width:520,child:Form(key:form,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[for(final f in widget.config.fields)...[field(f),const SizedBox(height:12)]])))),actions:[TextButton(onPressed:saving?null:()=>Navigator.pop(context),child:const Text('Отмена')),FilledButton(onPressed:saving?null:save,child:const Text('Сохранить'))]);
Widget field(FieldConfig f){if(f.kind==FieldKind.boolean)return SwitchListTile(value:bools[f.name]??false,title:Text(f.label),onChanged:(v)=>setState(()=>bools[f.name]=v));if(f.kind==FieldKind.relation)return DropdownButtonFormField<String>(value:relations[f.name],decoration:InputDecoration(labelText:f.label,border:const OutlineInputBorder()),items:[for(final o in options[f.name]??const[])DropdownMenuItem(value:'${o['id']}',child:Text('${o[f.relationLabelField]??o['id']}'))],onChanged:(v)=>setState(()=>relations[f.name]=v),validator:(v)=>server[f.name]??(f.required&&v==null?'Выберите значение':null));if(f.kind==FieldKind.multiRelation)return FormField<Set<String>>(initialValue:multi[f.name]??<String>{},builder:(state)=>InputDecorator(decoration:InputDecoration(labelText:f.label,border:const OutlineInputBorder(),errorText:server[f.name]),child:Wrap(spacing:8,runSpacing:8,children:[for(final o in options[f.name]??const[])FilterChip(label:Text('${o[f.relationLabelField]??o['id']}'),selected:(multi[f.name]??<String>{}).contains('${o['id']}'),onSelected:(selected){final set=multi.putIfAbsent(f.name,()=> <String>{});setState(()=>selected?set.add('${o['id']}'):set.remove('${o['id']}'));state.didChange(set);})])));return TextFormField(controller:ctrls[f.name],keyboardType:f.kind==FieldKind.number?TextInputType.number:null,decoration:InputDecoration(labelText:f.label,border:const OutlineInputBorder()),validator:(v){if(server[f.name]!=null)return server[f.name];if(f.required&&(v==null||v.trim().isEmpty))return 'Обязательное поле';if(f.kind==FieldKind.number&&v!=null&&v.isNotEmpty&&double.tryParse(v)==null)return 'Введите число';return null;});}}
